# Generated by Django 4.1.2 on 2022-10-28 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                ("barcode", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Dairy Products", "dairy_products"),
                            ("Beverages", "beverages"),
                            ("Baking Goods", "baking_goods"),
                            ("Frozen Foods", "frozen_foods"),
                            ("Meat", "meat"),
                            ("Cleaners", "cleaners"),
                            ("Paper Goods", "paper_goods"),
                            ("Personal Care", "personal_care"),
                            ("Other", "other"),
                        ],
                        default="Other",
                        max_length=50,
                    ),
                ),
                ("expiration_date", models.DateField()),
                ("is_exist", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.shop",
                    ),
                ),
            ],
        ),
    ]
