
volumes:
  postgres_data:
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "
      python manage.py migrate
      && python manage.py test
      && python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - 8000:8000
    env_file:
      - .envs/compose/django
    volumes:
      - .:/app
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .envs/compose/postgres